### ISSUE TITLE
sorted.npy generation

### ISSUE THREAD

**Issue by swayam01** [Kirili4ik/dla-ht2#1]
Thanks for sharing your work, How did you generate the sorted indexes sorted.npy file.
pls share pointers to generate same on new dataset

thanks for the help in advance!!

**Comment by Kirili4ik** [comment]
Hi!

I'm afraid I don't have the code to share, sorry. But it is just "sorted by length of sound indexes of samples".  So I'd imagine it could be done by a script that:
1) Creates a python list(?) of pairs [(index-1, length-1), (index-2, length-2), ...]
2) sorts that list(?) by the lengths (2nd argument)
3) saves the indexes in the right order

It can be probably made a lot more efficient =)
BTW, afair this is not necessary, but should speed up training a bit.

**Comment by swayam01** [comment]
Thanks a lot for your valuable response, i was able to fix the issues and train it on custom data for Hindi ASR.
